In [1]:
import numpy as np
import cv2 as cv

# Basic

In [ ]:
#a = np.array([[[1, 2, 3], [3, 2, 1]], [[4, 5, 6], [6, 5, 4]], [[7, 8, 9],[9, 8, 7]]])
# print(a)
# print(a.ndim)
#np.array(([1], [2], [3]), dtype = 'float32')
a1 = np.array([1, 2, 3, 4])
a2 = np.array(([[1], [2], [3], [4, 5, 6]]), dtype = 'object')
print(a1)
print(f'a1.shape: {a1.shape}')  #Return (r, c)
print(f'a1.ndim: {a1.ndim}')  #Return num of demention
print()
print('=====')
print(a2)
print(type(a2))
print(f'a2.shape: {a2.shape}')  #Return (r, c)
print(f'a2.ndim: {a2.ndim}')  #Return num of demention

# a2 = np.array([[1, 2, 3],
#               [4, 5, 6]])
# print(type(a2))
# print(a2.shape)  #Return (r, c)
# print(a2.ndim)
# a2.dtype
# a2.size  #Total elemnts in matrix

In [ ]:
my_a = np.array([[[1,2 ,3],
                 [4, 5, 6]],
                 [[7, 8, 9],
                 [10, 11, 12]],
                 [[13, 14, 15],
                 [16, 17, 18]]])
print(my_a)
print(type(my_a))
print("Shape:", my_a.shape)  #Return a tuple () with number of row and column
print("Total dimetion:", my_a.ndim)
print("Size: ", my_a.size)

# my_b = np.array([1, 2, 3])
# print(my_b)
# print(my_b.shape)
# print(my_b.ndim)

# Creat numpay array

In [ ]:
# Creat a numpy array fill with 0
zero_arr = np.zeros([2, 4], dtype = int)
print(zero_arr)

In [ ]:
#Creat a numpy array fill with 1
np.ones((3, 5), dtype = int)
#print(one_arr)

In [ ]:
#Creat a numpy array fill with num from a range
range_arr = np.arange(0, 18, 3)
print(range_arr)

In [ ]:
#Creat a numpy array fill with a given num
full_arr = np.full((3, 5), 77)
print(full_arr)

# Random

In [ ]:
#Creat a numpy array fill wil num in a range devide by step
lin_arr = np.linspace(0, 60, 6)
print(lin_arr)

In [ ]:
# #Random
# ran_arr = np.random.random([4, 4])
# print(ran_arr)
# print()

#Seed: Make sure that random number is unchange
np.random.seed(10)
seed_ran_arr = np.random.random((4, 4))
print(seed_ran_arr)
print()

#Normal: Creat a numpy array fill with randowm number in range loc +- scale 
nor_arr = np.random.normal(0, 1, (3, 3))
print(nor_arr)
print()
#Randint
randint_arr = np.random.randint(0, 10, (4, 5))
print(randint_arr)
print()
#Rand: Creat a numpy array with give size, fill with random num between 0 and 1
rand_arr = np.random.rand(1, 2)
print(rand_arr)

# Slicing and indexing

In [ ]:
#Indexing and slicing

#Indexing
#One dimension
my_x = np.random.randint(0, 20, 6)
print(my_x)

In [ ]:
print(my_x[0], my_x[-1])

In [ ]:
#Multi dimension
#2D
np.random.seed(10)
my_x2 =  np.random.randint(0, 10, (3, 4))
print(my_x2)
print(my_x2.ndim)



In [ ]:
#3D
np.random.seed(10)
my_3d = np.random.randint(0, 3, ((3, 3, 3)))
print(my_3d)
print(my_3d.ndim)

print(my_3d.shape)

my_3d_tem = np.array([[[1, 1, 0], [0, 1, 0], [1, 1, 0]],
                    [[1, 1, 2], [0, 1, 0], [2, 0, 2]],
                    [[0, 0, 0], [2, 0, 2], [2, 1, 0]]])
print(my_3d_tem)

In [ ]:
print(my_x2[0, 0])
my_x2[1, 0] = 8888
print(my_x2)

In [ ]:
#Slicing
#One dimension
print(my_x)
print(my_x[0:3])
print(my_x[::2]) #Slicing whole array with step

In [ ]:
#Multi dimention
#2D
print(my_x2)
print()
print(my_x2[:2, :3])  #Slicing 2 first row and 3 first column
print()
print(my_x2[:, :2]) #Slicing whole row and 2 first column

In [ ]:
#3D
my_3d_tem = np.array([[[1, 1, 0, 7], [0, 1, 0, 7], [1, 1, 0, 7], [0, 0, 0, 7]],
                    [[1, 1, 2, 7], [0, 1, 0, 7], [2, 0, 2, 7], [0, 0, 0, 7]],
                    [[0, 0, 0, 7], [2, 0, 2, 7], [2, 1, 0, 7], [0, 0, 0, 7]]])

print(my_3d_tem)
print(my_3d_tem.shape)
print()
a = my_3d_tem[1, 2, -2:]
print(a)

In [3]:
#Reshaping array
# grid_arr = np.arange(1, 10)
# print(grid_arr)
# print(grid_arr.shape)
# print(grid_arr.reshape((3, 3)))

# my_2d = np.array([[1, 2, 3, 4],
#                   [5, 6, 7, 8],
#                   [9, 10, 11, 12]])
# print(my_2d)
# print(my_2d.shape)
# print(my_2d.ndim)
# print()

# my_test_1d = my_2d.flatten()
# print(my_test_1d)

# my_test_2d_back = np.reshape(my_test_1d, (3, 4))
# print(my_test_2d_back)

img = cv.imread('IMG_0669.JPG')

img = img.astype(np.uint8)
print(img.dtype)
# cv.imshow('Pic', img)
# cv.waitKey(0)

b, g, r = cv.split(img)
print(b.dtype)
# cv.imshow('Pic', b)
# cv.waitKey(0)

print(b)
print(b.shape)
print(b.ndim)
print()
b_1d = b.flatten()
print(b_1d)
print(b_1d.dtype)
print()
np.savetxt('test.csv', b_1d, fmt = '%s')

b_1d_back = np.loadtxt('test.csv', dtype = np.uint8)
print(b_1d_back)
print('_____')
b_back = np.reshape(b_1d_back, b.shape)
print(b_back)
cv.imshow('Pic', b_back)
cv.waitKey(0)

uint8
uint8
[[ 82  80  81 ... 101 101 104]
 [ 81  79  80 ... 100 100 102]
 [ 79  80  80 ...  99 100 101]
 ...
 [ 41  37  37 ... 183 186 189]
 [ 39  36  38 ... 185 189 192]
 [ 36  33  37 ... 186 190 193]]
(5472, 3648)
2

[ 82  80  81 ... 186 190 193]
uint8

[ 82  80  81 ... 186 190 193]
_____
[[ 82  80  81 ... 101 101 104]
 [ 81  79  80 ... 100 100 102]
 [ 79  80  80 ...  99 100 101]
 ...
 [ 41  37  37 ... 183 186 189]
 [ 39  36  38 ... 185 189 192]
 [ 36  33  37 ... 186 190 193]]


-1

In [ ]:
#Transpose
#Swith between row and column
tran_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tran_arr)

print(tran_arr.T)

In [ ]:
#Concatenation (nối) and spliting(tách)

#Concatenation
conca_x_arr = np.array([1, 2, 3])
conca_y_arr = np.array([5, 6, 7, 8])
np.concatenate((conca_x_arr, conca_y_arr))

In [ ]:
grid_1 = np.array([[1, 2, 3], [4, 5, 6]])
grid_2 = np.array([[7, 8, 9], [10, 11, 12]])
by_column = np.concatenate((grid_1, grid_2))
print(by_column)
print()
by_row = np.concatenate((grid_1, grid_2), axis = 1)
print(by_row)

In [ ]:
#vstack: put 2 array toghther by column (row unchange)
v_stack = np.vstack((conca_x_arr, grid_1))
print(v_stack)
print()
#hstack: put 2 array together by row (column unchange)
h_stack = np.hstack((grid_2, grid_1))
print(h_stack)

In [ ]:
#Slipting
slip_x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.split(slip_x, [3, 4])

In [ ]:
#Broadcasing
#Rules: Broadcasing is allow if:
#Small array size = 1
#Small array's column = large array's column and row = 1
#Small array's row = large array's row and column = 1
#(a, 1) array and (1, b) array. Resul is new array (a, b)
a = np.array([[1, 2, 3], [3, 2, 1], [1, 2, 3], [3, 2, 1]])
print(a)

In [ ]:
#1 Rule
print(a * 10)

In [ ]:
#2 Rule
b = np.array([2, 3, 4])
print(b.shape)
print(b * a)

In [ ]:
#3 Rule
c = np.array([[4], [3], [3], [1]])
print(c.shape)
print(a * c)

In [ ]:
#4 Rule
a_row = np.array([2, 4, 6, 8])
a_col = np.array([[1], [3], [5]])
print(f"a_row = {a_row.shape}")
print(f"a_col = {a_col.shape}")
print(a_row * a_col)

In [ ]:
#Manipulating & comparing array
#Aggregation
ll = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
print(ll)

In [ ]:
sum(ll)  #Build-in sum func

In [ ]:
np.sum(ll)  #numpy sum func

In [ ]:
np.max(ll)

In [ ]:
np.min(ll)

In [ ]:
np.mean(ll)  #Give average value

In [ ]:
np.std(ll)  #Độ lệch chuẩn (Độ phân toán dữ liệu), bằng căn bặc 2 của phương sai

In [ ]:
np.var(ll)  #Phương sai (trung bình cộng của bình phương hiệu của dữ liệu thật và giá trị trung bình)

In [ ]:
#Sorting array
new_x = np.array([7, 3414, 134, 687, 435354, 633, 72])
np.sort(new_x)

In [ ]:
np.argsort(new_x)  #Sort and return index

In [ ]:
#Sort row and colomn
np.random.seed(42)
matrix_a = np.random.randint(0, 10, size = (4, 6))
print(matrix_a)
print(matrix_a.shape[0])

In [ ]:
np.sort(matrix_a, axis = 0)  #Sort by column

In [ ]:
np.sort(matrix_a, axis = 1)  #Sort by row

In [ ]:
#Linear Algebra - Đại số tuyến tính/Nhân ma trận
#Số cột của ma trận một phải bằng số hàng của ma trận hai
#(a, x) dot (y, a) is ok
#Ma trận mới có số hàng của ma trận một, cột của ma trận hai
# A = np.array([[1, 2, 3],
#              [4, 5, 6],
#              [7, 8, 9]])
B = np.array([[6, 5, 10, 15, 20],
             [4, 3, 6, 7, 8],
             [2, 1, 6, 8, 7]])
# print(A.shape)
print(B.shape)
# print(A.dot(B))
# print((A.dot(B).shape))
C = np.array([2, 3, 4, 5, 6])
print(C.shape)
print(B.dot(C))
print((B.dot(C).shape))

In [ ]:
#Dot product
h = np.array([1, 2, 3])
print(h.shape)
print(h.reshape(1, 3))